import { defineConfig } from 'vite-plus'

// oxlint-disable-next-line import/no-default-export -- Vite resolves the config through its default export
export default defineConfig({
  lint: {
    ignorePatterns: ['**/node_modules/**', 'out/**'],
    // Node-only script: declaring the runtime is what lets rules that resolve globals
    // (`no-undef`, `unicorn/prefer-global-this`) tell a real global apart from a typo.
    env: { node: true, es2024: true },
    // Setting `plugins` replaces oxlint's default list — restate the defaults, then add
    // import / promise / node.
    plugins: ['typescript', 'unicorn', 'oxc', 'import', 'promise', 'node'],
    options: {
      typeAware: true,
      typeCheck: true,
      // A rule that stops firing must have its `oxlint-disable` comment deleted with it,
      // otherwise the suppression silently outlives its reason.
      reportUnusedDisableDirectives: 'deny',
      denyWarnings: true,
    },
    categories: {
      correctness: 'error',
      suspicious: 'error',
      perf: 'error',
    },
    // The same list packages/valibot-to-openapi holds itself to, minus the rules that only
    // describe a library's internals. Rules in the correctness / suspicious / perf categories
    // are already errors via `categories` above and are not restated.
    rules: {
      eqeqeq: 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-param-reassign': ['error', { props: true }],
      'no-shadow': 'error',
      'no-underscore-dangle': 'error',
      'no-unused-vars': 'error',
      'no-plusplus': 'error',
      'no-await-in-loop': 'error',
      'no-undef': 'error',
      // A script prints its report on purpose.
      'no-console': 'off',
      'typescript/no-explicit-any': 'error',
      'typescript/no-non-null-assertion': 'error',
      'typescript/consistent-type-imports': 'error',
      'typescript/consistent-type-assertions': ['error', { assertionStyle: 'never' }],
      'typescript/no-unsafe-type-assertion': 'error',
      'typescript/no-unnecessary-type-assertion': 'error',
      'typescript/no-floating-promises': 'error',
      'typescript/await-thenable': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/require-await': 'error',
      'typescript/return-await': 'error',
      'typescript/prefer-readonly': 'error',
      'typescript/prefer-nullish-coalescing': 'error',
      'typescript/prefer-optional-chain': 'error',
      'typescript/switch-exhaustiveness-check': 'error',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-assignment': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-deprecated': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/restrict-template-expressions': 'error',
      'typescript/restrict-plus-operands': 'error',
      'typescript/only-throw-error': 'error',
      'typescript/no-confusing-void-expression': 'error',
      'typescript/use-unknown-in-catch-callback-variable': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/prefer-ts-expect-error': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-invalid-void-type': 'error',
      'typescript/non-nullable-type-assertion-style': 'error',
      'typescript/consistent-type-definitions': ['error', 'type'],
      'typescript/consistent-type-exports': 'error',
      'typescript/array-type': 'error',
      'typescript/method-signature-style': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/dot-notation': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/prefer-find': 'error',
      'typescript/prefer-includes': 'error',
      'typescript/prefer-string-starts-ends-with': 'error',
      // ESM-only workspace: a `require` call would not resolve.
      'typescript/no-require-imports': 'error',
      'typescript/no-import-type-side-effects': 'error',
      'no-throw-literal': 'error',
      'unicorn/error-message': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/prefer-module': 'error',
      'unicorn/prefer-global-this': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/require-module-specifiers': 'error',
      'unicorn/prefer-export-from': 'error',
      'unicorn/prefer-import-meta-properties': 'error',
      'unicorn/no-abusive-eslint-disable': 'error',
      'prefer-template': 'error',
      'no-useless-concat': 'error',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-at': 'error',
      'unicorn/explicit-length-check': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-spread': 'error',
      'unicorn/prefer-string-replace-all': 'error',
      'unicorn/prefer-object-from-entries': 'error',
      'unicorn/no-array-for-each': 'error',
      'unicorn/no-array-sort': 'error',
      'unicorn/no-await-expression-member': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/consistent-empty-array-spread': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'require-unicode-regexp': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/throw-new-error': 'error',
      'unicorn/catch-error-name': ['error', { name: 'error' }],
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      curly: ['error', 'multi-line'],
      'no-else-return': 'error',
      'no-lonely-if': 'error',
      'unicorn/no-lonely-if': 'error',
      'no-useless-return': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'array-callback-return': 'error',
      'no-loop-func': 'error',
      'block-scoped-var': 'error',
      'init-declarations': 'error',
      'no-redeclare': 'error',
      'no-multi-assign': 'error',
      'no-sequences': 'error',
      'no-useless-assignment': 'error',
      'no-use-before-define': ['error', { functions: false }],
      'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
      'arrow-body-style': 'error',
      'prefer-arrow-callback': 'error',
      'guard-for-in': 'error',
      yoda: 'error',
      'no-self-compare': 'error',
      'object-shorthand': 'error',
      'operator-assignment': 'error',
      'prefer-object-spread': 'error',
      'prefer-object-has-own': 'error',
      'no-object-constructor': 'error',
      'no-array-constructor': 'error',
      'unicorn/new-for-builtins': 'error',
      'no-implicit-globals': 'error',
      'symbol-description': 'error',
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-return-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-bitwise': 'error',
      'no-void': ['error', { allowAsStatement: true }],
      'no-empty': 'error',
      'no-empty-function': 'error',
      'unicode-bom': 'error',
      'no-warning-comments': 'error',
      'promise/param-names': 'error',
      'promise/valid-params': 'error',
      'promise/no-return-wrap': 'error',
      'promise/no-nesting': 'error',
      'promise/catch-or-return': 'error',
      'promise/always-return': 'error',
      'promise/prefer-catch': 'error',
      'node/no-exports-assign': 'error',
      'node/no-path-concat': 'error',
      'node/handle-callback-err': 'error',
      // Relative specifiers stay `.js`/`.ts`-suffixed, which NodeNext resolution requires at
      // runtime and `tsc` does not check.
      'import/extensions': ['error', 'always', { ignorePackages: true }],
      'import/export': 'error',
      'import/first': 'error',
      'import/unambiguous': 'error',
      'import/no-commonjs': 'error',
      'import/no-cycle': 'error',
      'import/no-self-import': 'error',
      'import/no-duplicates': 'error',
      'import/no-default-export': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-absolute-path': 'error',
      'import/no-empty-named-blocks': 'error',
      'import/no-named-default': 'error',
      'import/no-unassigned-import': 'error',
      'import/no-named-as-default': 'error',
      'import/consistent-type-specifier-style': 'error',
      'no-shadow-restricted-names': 'error',
      'no-delete-var': 'error',
      'unicorn/filename-case': 'error',
    },
  },
  // Style (printWidth / quotes / semicolons / import sorting) is inherited from the root
  // vite.config.ts; only the paths this workspace skips are declared here.
  fmt: {
    ignorePatterns: ['**/node_modules/**', 'out/**'],
  },
})
